import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('test_generatora_1.txt', sep=" ", header=None)
data2 = pd.read_csv('test_generatora_2.txt', sep=" ", header=None)
plt.subplots(figsize=(8, 5))
plt.grid(linestyle='--')
plt.xlabel("X")
plt.ylabel("Y")
plt.plot(data[0], data[1], 'o', markersize=1, alpha=1, label='$R_a=2$')
plt.plot(data2[0], data2[1], 'o', markersize=1, alpha=1, label='$R_b=2\sqrt{2}$')
plt.legend(markerscale=7)
plt.ylim(-3,3)
plt.savefig('test_generatora.png')
plt.show()

df1 = pd.read_csv('pow_A_0.txt', sep=" ", header=None)
df2 = pd.read_csv('pow_B_0.txt', sep=" ", header=None)
#plt.subplots(figsize=(4, 2.5))
plt.grid(linestyle='--')
plt.title("$x_a = 0$")
plt.xlim(10, 10000000)
#plt.ylim(12.54, 12.58)
plt.ylabel("$\mu_1$")
plt.xlabel('N')
plt.xscale('log')
plt.errorbar(df1[0], df1[1], yerr=df1[2], mec="k", capthick=True, fmt='o', label='$K_a$', capsize=5)
plt.errorbar(df2[0], df2[1], yerr=df2[2], mec="k", capthick=True, fmt='o', label='$K_b$', capsize=5)
plt.legend(fontsize='large')
plt.savefig('pow_0.png')
plt.show()
df3 = pd.read_csv('pow_A_xa.txt', sep=" ", header=None)
df4 = pd.read_csv('pow_B_xa.txt', sep=" ", header=None)
#plt.subplots(figsize=(4, 2.5))
plt.grid(linestyle='--')
plt.title('$x_a = R_b + 0.5R_a$')
plt.xlim(10, 10000000)
plt.ylabel("$\mu_1$")
plt.xlabel('N')
plt.xscale('log')
plt.errorbar(df3[0], df3[1], yerr=df3[2], mec="k", capthick=True, fmt='o', label='$K_a$', capsize=5)
plt.errorbar(df4[0], df4[1], yerr=df4[2], mec="k", capthick=True, fmt='o', label='$K_b$', capsize=5)
plt.legend(fontsize='large')
plt.savefig('pow_xa.png')
plt.show()